### ISSUE TITLE
Doesn't implement interface negroni.ResponseWriter

### ISSUE THREAD

**Issue by EugeneKrapivin** [meatballhat/negroni-logrus#5]
There is a compatibility problem with the casting the current version of `RecorderResponseWriter` to the current version of `negroni.ResponseWriter`

```
INFO[0002] started handling request                      method=GET remote=127.0.0.1:38527 request=/stats
2015/08/06 17:09:09 http: panic serving 127.0.0.1:38527: interface conversion: *stats.RecorderResponseWriter is not negroni.ResponseWriter: missing method Before
goroutine 29 [running]:
net/http.func·011()
	/usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x75efc0, 0xc208041c80)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc208108de0, 0x7fbe64fc1ff8, 0xc208109900, 0xc20811e340, 0xc208109920)
	/home/nocgod/Go/src/github.com/meatballhat/negroni-logrus/middleware.go:50 +0x465
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fbe64fc1cd8, 0xc208108de0, 0xc208108fc0, 0x7fbe64fc1ff8, 0xc208109900, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7fbe64fc1ff8, 0xc208109900, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:33 +0x56
github.com/thoas/stats.(*Stats).ServeHTTP(0xc208004960, 0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340, 0xc2081098e0)
	/home/nocgod/Go/src/github.com/thoas/stats/stats.go:61 +0xb4
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fbe64fc1cb0, 0xc208004960, 0xc208108fa0, 0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:33 +0x56
github.com/codegangsta/negroni.func·001(0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340, 0xc208109860)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:42 +0x7d
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc2080012f0, 0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340, 0xc208109860)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fbe64fc1c60, 0xc2080012f0, 0xc208108f80, 0x7fbe64fc1ed8, 0xc208041b80, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc208116990, 0x7fbe64fc1e40, 0xc2080d2820, 0xc20811e340)
	/home/nocgod/Go/src/github.com/codegangsta/negroni/negroni.go:73 +0x10a
net/http.serverHandler.ServeHTTP(0xc208004a80, 0x7fbe64fc1e40, 0xc2080d2820, 0xc20811e340)
	/usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2080da280)
	/usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
```

They've added a method `Before` on the interface.

naive fix (puts a dependency on negroni)
```Golang
func (rw *RecorderResponseWriter) Before(before func(negroni.ResponseWriter)) {
	before(rw)
}
```
to recorder.go

**Comment by meatballhat** [comment]
@EugeneKrapivin Hey sorry for the delay.  I'm having trouble understanding why this should be added to negroni-logrus.  What is this `*RecorderResponseWriter` type?

**Comment by jszwedko** [comment]
Looks like `RecorderResponseWriter` is part of the https://github.com/thoas/stats middleware.

@EugeneKrapivin I think you mean to open this issue on that repository -- you are correct in that it doesn't match the interface signature for `negroni.ResponseWriter`.

**Comment by EugeneKrapivin** [comment]
@jszwedko I think you are right, my bad.
@meatballhat Sorry for bothering you mate.
